apiVersion: v1
kind: Secret
metadata:
  name: wordpress-azure-mysql-secret
type: Opaque
stringData:
  # IMPORTANT: Replace these with your ACTUAL Azure MySQL Flexible Server details.
  # Do NOT commit these values directly to Git for production.
  # Use a secrets management solution (e.g., Azure Key Vault + CSI Driver for Secrets Store)
  # or Sealed Secrets in production.

  # Your Azure Database for MySQL Flexible Server's fully qualified domain name (FQDN).
  # You can find this in the Azure Portal on your MySQL server's "Overview" page.
  WORDPRESS_DB_HOST: "myflexmysql-19-06-2025.mysql.database.azure.com" # Example: mymysqlserver.mysql.database.azure.com

  # The admin username for your Azure MySQL Flexible Server.
  # Typically ends with @yourservername (e.g., myadmin@mymysqlserver).
  WORDPRESS_DB_USER: "mysqladmin" # Example: adminuser@mymysqlserver

  # The password for your Azure MySQL Flexible Server admin user.
  WORDPRESS_DB_PASSWORD: "YourStrongPassword123!" # Your strong password

  # The name of the database you created within your Azure MySQL Flexible Server.
  WORDPRESS_DB_NAME: "wordpress_db" 

---

apiVersion: v1
kind: Secret
metadata:
  name: wordpress-auth-secret
  namespace: wordpress
type: Opaque
stringData:
  # Generate new salts from https://api.wordpress.org/secret-key/1.1/salt/
  # IMPORTANT: Replace these with freshly generated values
  WORDPRESS_AUTH_KEY: "8+cJUy/{,-tw+>><c?<P2vYAY15>>P<9=P1%5mS^-Q0[OdoSqf5#76@,;0jf96p^"
  WORDPRESS_SECURE_AUTH_KEY: "J4:wjG;)O^E-G.|V}4e>eR/-9GhITlZUt@Noo%NjZl@d?=d#[vg7_B>g<mYQz>SP"
  WORDPRESS_LOGGED_IN_KEY: "%&MSB>r|/VM;-Ci_<22*E9q.Oam38zX6tl`I]5te8</r+cZ@9`+~602~.:A}gZyh"
  WORDPRESS_NONCE_KEY: "@:P UGb@DUE;$JY-vH=g<Ka~1-R(z 74qH&jl=;.7x(B4PpC|0:1bl_[Wxq`|X$."
  WORDPRESS_AUTH_SALT: "N9i7Tw0-c,O57(^rHU[!OPzq]`T:!doK5Yoq/=-lOvtEC`u+6Nj8.(x=BZ3TJ+f="
  WORDPRESS_SECURE_AUTH_SALT: "geW+7A$narMR=N.f,H/ee=yGZu@O+Q(CPMx+?S<jdBIq[~Ax_EWD]e!3C!(?mf$$"
  WORDPRESS_LOGGED_IN_SALT: "hBx[#}y?lA:+1>+Ya1GhqWj,~897Re`VtOG1A=@^k-U2Wtbjo3!pLZv*C&BiDUd"
  WORDPRESS_NONCE_SALT: "42e&f+Oi$ed{H=D>`{0`P{dgfDb*emyin7++wG|1.lLwAuaL/+,S?u>qqtU2IUk#"