apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
  namespace: wordpress
data:
  custom.ini: |
    upload_max_filesize = 100M
    post_max_size = 100M
    max_input_time = 600
    max_execution_time = 600
    memory_limit = 1024M
    max_input_vars = 3000
    display_errors = On
    display_startup_errors = On
    log_errors = On
    error_log = /var/log/apache2/php_errors.log
    error_reporting = E_ALL
    session.gc_maxlifetime = 7200
    session.cookie_lifetime = 7200
    allow_url_fopen = On
    allow_url_include = Off
    user_agent = "WordPress"
    auto_detect_line_endings = Off



